pub struct ToolSpec {
    pub name: &'static str,
    pub description: &'static str,
    pub input_schema_json: &'static str,
    pub deprecated: bool,
    pub aliases: &'static [&'static str],
    pub requires_serialized_dispatch: bool,
    pub category: &'static str,
}

const EMPTY_SCHEMA: &str = r#"{"type":"object","additionalProperties":true}"#;

static TOOLS: &[ToolSpec] = &[
    ToolSpec {
        name: "ping",
        description: "Health probe for plugin liveness and runtime status.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: false,
        category: "process",
    },
    ToolSpec {
        name: "get_process_info",
        description: "Return attached process summary.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: false,
        category: "process",
    },
    ToolSpec {
        name: "enum_modules",
        description: "Enumerate loaded modules.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: false,
        category: "process",
    },
    ToolSpec {
        name: "get_thread_list",
        description: "Enumerate target threads.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: false,
        category: "process",
    },
    ToolSpec {
        name: "get_symbol_address",
        description: "Resolve a symbol or expression to an address.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: true,
        category: "process",
    },
    ToolSpec {
        name: "get_address_info",
        description: "Resolve address metadata.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: true,
        category: "process",
    },
    ToolSpec {
        name: "normalize_address",
        description: "Normalize an address to module-relative metadata.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: false,
        category: "process",
    },
    ToolSpec {
        name: "get_rtti_classname",
        description: "Recover RTTI class name from an object address.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: true,
        category: "process",
    },
    ToolSpec {
        name: "get_module_fingerprint",
        description: "Return build-oriented module fingerprint metadata.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: false,
        category: "process",
    },
    ToolSpec {
        name: "read_memory",
        description: "Read raw bytes from process memory.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: false,
        category: "memory",
    },
    ToolSpec {
        name: "read_integer",
        description: "Read numeric values from process memory.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: false,
        category: "memory",
    },
    ToolSpec {
        name: "read_string",
        description: "Read ANSI or UTF-16 strings from memory.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: false,
        category: "memory",
    },
    ToolSpec {
        name: "read_pointer",
        description: "Read a pointer value from memory.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: false,
        category: "memory",
    },
    ToolSpec {
        name: "read_pointer_chain",
        description: "Resolve a multi-level pointer chain.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: false,
        category: "memory",
    },
    ToolSpec {
        name: "write_integer",
        description: "Write numeric values into memory.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: false,
        category: "memory",
    },
    ToolSpec {
        name: "write_memory",
        description: "Write raw bytes into memory.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: false,
        category: "memory",
    },
    ToolSpec {
        name: "write_string",
        description: "Write strings into memory.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: false,
        category: "memory",
    },
    ToolSpec {
        name: "batch_get_address_info",
        description: "Resolve address metadata in batch.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: true,
        category: "batch",
    },
    ToolSpec {
        name: "batch_read_memory",
        description: "Read multiple memory regions in one call.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: false,
        category: "batch",
    },
    ToolSpec {
        name: "batch_disassemble",
        description: "Disassemble multiple ranges in one call.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: true,
        category: "batch",
    },
    ToolSpec {
        name: "scan_all",
        description: "Start an initial value scan.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: false,
        category: "scan",
    },
    ToolSpec {
        name: "get_scan_results",
        description: "Fetch current scan results.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: false,
        category: "scan",
    },
    ToolSpec {
        name: "next_scan",
        description: "Refine a previous scan result set.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: false,
        category: "scan",
    },
    ToolSpec {
        name: "aob_scan",
        description: "Search memory for an AOB signature.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: false,
        category: "scan",
    },
    ToolSpec {
        name: "search_string",
        description: "Search readable memory for strings.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: false,
        category: "scan",
    },
    ToolSpec {
        name: "generate_signature",
        description: "Build a signature candidate around an address.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: false,
        category: "scan",
    },
    ToolSpec {
        name: "get_memory_regions",
        description: "Return useful committed memory regions.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: false,
        category: "scan",
    },
    ToolSpec {
        name: "enum_memory_regions_full",
        description: "Enumerate the full memory map.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: false,
        category: "scan",
    },
    ToolSpec {
        name: "checksum_memory",
        description: "Compute an MD5 checksum for a memory region.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: false,
        category: "scan",
    },
    ToolSpec {
        name: "disassemble",
        description: "Disassemble instructions from a target range.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: true,
        category: "analysis",
    },
    ToolSpec {
        name: "get_instruction_info",
        description: "Decode a single instruction with metadata.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: true,
        category: "analysis",
    },
    ToolSpec {
        name: "find_function_boundaries",
        description: "Locate function start and end boundaries.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: true,
        category: "analysis",
    },
    ToolSpec {
        name: "analyze_function",
        description: "Extract call relationships from a function body.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: true,
        category: "analysis",
    },
    ToolSpec {
        name: "find_references",
        description: "Find instructions that reference a target address.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: true,
        category: "analysis",
    },
    ToolSpec {
        name: "find_call_references",
        description: "Find call sites that target a function address.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: true,
        category: "analysis",
    },
    ToolSpec {
        name: "dissect_structure",
        description: "Heuristically infer object or structure field layout.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: true,
        category: "analysis",
    },
    ToolSpec {
        name: "set_breakpoint",
        description: "Set an execution breakpoint.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: true,
        category: "debug",
    },
    ToolSpec {
        name: "set_data_breakpoint",
        description: "Set a data breakpoint.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: true,
        category: "debug",
    },
    ToolSpec {
        name: "remove_breakpoint",
        description: "Remove a breakpoint by id.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: true,
        category: "debug",
    },
    ToolSpec {
        name: "list_breakpoints",
        description: "List active breakpoints.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: true,
        category: "debug",
    },
    ToolSpec {
        name: "clear_all_breakpoints",
        description: "Clear all active breakpoints.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: true,
        category: "debug",
    },
    ToolSpec {
        name: "get_breakpoint_hits",
        description: "Return captured breakpoint hit records.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: true,
        category: "debug",
    },
    ToolSpec {
        name: "get_physical_address",
        description: "Translate a virtual address to a physical address.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: true,
        category: "debug",
    },
    ToolSpec {
        name: "start_dbvm_watch",
        description: "Start a DBVM watch tracing session.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: true,
        category: "debug",
    },
    ToolSpec {
        name: "stop_dbvm_watch",
        description: "Stop a DBVM watch session and return final results.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: true,
        category: "debug",
    },
    ToolSpec {
        name: "poll_dbvm_watch",
        description: "Poll intermediate DBVM watch results.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: true,
        category: "debug",
    },
    ToolSpec {
        name: "evaluate_lua",
        description: "Execute a Lua snippet inside Cheat Engine.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: true,
        category: "script",
    },
    ToolSpec {
        name: "evaluate_lua_file",
        description: "Execute a local Lua file inside Cheat Engine.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: true,
        category: "script",
    },
    ToolSpec {
        name: "auto_assemble",
        description: "Execute an Auto Assembler script.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: true,
        category: "script",
    },
    ToolSpec {
        name: "auto_assemble_file",
        description: "Execute a local Auto Assembler file.",
        input_schema_json: EMPTY_SCHEMA,
        deprecated: false,
        aliases: &[],
        requires_serialized_dispatch: true,
        category: "script",
    },
];

pub fn all_tools() -> &'static [ToolSpec] {
    TOOLS
}

pub fn find_tool(name: &str) -> Option<&'static ToolSpec> {
    TOOLS.iter().find(|tool| tool.name == name)
}

pub fn canonical_name(name: &str) -> &str {
    name
}
