-- ce-mcp embedded Lua backend bridge compatibility layer
--
-- v0.2.0 splits the historical monolithic bridge.lua into focused modules:
--   * common.lua   - shared process/memory/analysis handlers
--   * debug.lua    - breakpoint and DBVM tracing handlers
--   * script.lua   - raw Lua / AutoAssembler helpers
--   * dispatch.lua - command registry + dispatch entrypoints
--
-- This file stays intentionally thin so include paths remain stable for older
-- references while the actual implementation is assembled in mod.rs.
